config/routes.rb
RsvpApp::Application.routes.draw do
  resources :users

  resources :events do
    resources :invites, only: [:new]
  end

  resources :invites, only: [:index, :edit, :update]

  root 'events#index'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :invites
  has_many :users, :through => :invites
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :invites
  has_many :events, :through => :invites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(params.require(:event).permit(:name))
    redirect_to events_path
  end

  def show
    @event = Event.find(params[:id])
    @users = @event.users
    @invites = Invite.where(:event_id == @event.id)
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def new
    @user = User.new
    @event = Event.find(params[:event_id])
  end

  def edit
    @invite = Invite.find(params[:id])
  end

  def update
    @invite = Invite.find(params[:id])
    @invite.update(:attending => params[:invite][:attending])
    redirect_to event_path(@event)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.find_or_create_by(:name => params[:user][:name])
    @event = Event.find(params[:user][:event_id])
    @user.invites.build(:user_id => @user.id, :event_id => @event.id).save

    redirect_to event_path(@event)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h2>Available Events</h2>
<ul>
  <% @events.each do |event| %>
  <li><%= link_to event.name, event_path(event) %></li>
  <% end %>
</ul>
<%= link_to "Create a new event", new_event_path %>

app/views/events/new.html.erb
<h3>New Event</h3>
<%= form_for @event do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<h3><%= @event.name %></h3><br>
<h4>Invited users</h4>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, edit_invite_path(@invites.find_by(:user_id => user.id)) %></li>
  <% end %>
</ul>

<%= link_to "Invite a user", new_event_invite_path(@event) %><br>

<%= link_to "Index", events_path %>

app/views/invites/edit.html.erb
<%= form_for @invite do |f| %>
  <%= f.label :attending %>
  <%= f.text_field :attending %>

  <%= f.submit "RSVP" %>
<% end %>

app/views/invites/new.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name %>
  <%= f.hidden_field :event_id, :value => @event.id %>

  <%= f.submit "Invite to #{@event.name}" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RsvpApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>